In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests

### Önce sayfamızı yükleyelim ve sayfada gezinelim

In [2]:
url = "https://en.wikipedia.org/wiki/World_population"

### Web sayfasının içeriğini metin formatında alın ve 'data' adlı bir değişkende sakla.

In [3]:
headers = {
   "User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/154.0.0.0 Safari/537.36"
}

data = requests.get(url, headers=headers)
soup = BeautifulSoup(data.text, "html.parser")

### Web sayfasındaki tüm HTML tablolarını bul

In [5]:
tables = soup.find_all("table")
len(tables)

27

### En yoğun nüfuslu 10 ülke tablosunu aradığımızı varsayalım, tablolar listesine bakıp her tablodaki verilere göre aradığımız doğru olanı bulabiliriz veya tabloda varsa tablo adını arayabiliriz ancak bu seçenek her zaman işe yaramayabilir.

In [12]:
for index,table in enumerate(tables):
    if ("10 most densely populated countries" in str(table)):
        table_index = index
print(table_index)

5

### Aşağıda, en yoğun nüfuslu 10 ülkeyi gösteren tablonun adını bulup bulamayacağınıza bir bakın.

In [13]:
print(tables[table_index].prettify())

<table class="wikitable sortable" id="mwBLU" style="text-align:right">
 <caption id="mwBLY">
  10 most densely populated countries
  <small id="mwBLc">
   (with population above 5
   <span id="mwBLg" typeof="mw:Entity">
   </span>
   million)
  </small>
  <sup about="#mwt477" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":":10"},"body":{"id":"mw-reference-text-cite_note-:10-106"}}' id="cite_ref-:10_106-0" rel="dc:references" typeof="mw:Extension/ref">
   <a href="#cite_note-:10-106" id="mwBLk">
    <span class="mw-reflink-text" id="mwBLo">
     <span class="cite-bracket" id="mwBLs">
      [
     </span>
     101
     <span class="cite-bracket" id="mwBLw">
      ]
     </span>
    </span>
   </a>
  </sup>
 </caption>
 <tbody id="mwBL0">
  <tr id="mwBL4">
   <th id="mwBL8" scope="col">
    Rank
   </th>
   <th id="mwBMA" scope="col">
    Country
   </th>
   <th id="mwBME" scope="col">
    Population
   </th>
   <th id="mwBMI" scope="col">
    Area
    <br id="mwBMM"/>
    <small id="mwBMQ">
     (km
     <sup id="mwBMU">
      2
     </sup>
     )
    </small>
   </th>
   <th id="mwBMY" scope="col">
    Density
    <br id="mwBMc"/>
    <small id="mwBMg">
     (pop/km
     <sup id="mwBMk">
      2
     </sup>
     )
    </small>
   </th>
  </tr>
  <tr id="mwBMo">
   <td id="mwBMs">
    1
   </td>
   <td align="left" id="mwBMw">
    <span about="#mwt478" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Singapore"}},"i":0}}]}' id="mwBM0" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Singapore.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/40px-Flag_of_Singapore.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/60px-Flag_of_Singapore.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt478" href="https://en.wikipedia.org/wiki/Singapore" id="mwBM4" rel="mw:WikiLink" title="Singapore">
     Singapore
    </a>
   </td>
   <td id="mwBM8">
    5,921,231
   </td>
   <td id="mwBNA">
    719
   </td>
   <td id="mwBNE">
    8,235
   </td>
  </tr>
  <tr id="mwBNI">
   <td id="mwBNM">
    2
   </td>
   <td align="left" id="mwBNQ">
    <span about="#mwt479" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Bangladesh"}},"i":0}}]}' id="mwBNU" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="307" data-file-type="drawing" data-file-width="512" decoding="async" height="14" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Bangladesh.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/40px-Flag_of_Bangladesh.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/60px-Flag_of_Bangladesh.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt479" href="https://en.wikipedia.org/wiki/Bangladesh" id="mwBNY" rel="mw:WikiLink" title="Bangladesh">
     Bangladesh
    </a>
   </td>
   <td id="mwBNc">
    165,650,475
   </td>
   <td id="mwBNg">
    148,460
   </td>
   <td id="mwBNk">
    1,116
   </td>
  </tr>
  <tr id="mwBNo">
   <td id="mwBNs">
    3
   </td>
   <td align="left" id="mwBNw">
    <p id="mwBN0">
     <span about="#mwt480" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Palestine"}},"i":0}}]}' id="mwBN4" typeof="mw:Transclusion">
      <span class="mw-image-border" typeof="mw:File">
       <span>
        <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="1200" decoding="async" height="12" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Palestine.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/40px-Flag_of_Palestine.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/60px-Flag_of_Palestine.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
       </span>
      </span>
     </span>
     <a about="#mwt480" href="https://en.wikipedia.org/wiki/Palestine" id="mwBN8" rel="mw:WikiLink" title="Palestine">
      Palestine
     </a>
     <sup about="#mwt481" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-107"}}' id="cite_ref-107" rel="dc:references" typeof="mw:Extension/ref">
      <a data-mw-group="note" href="#cite_note-107" id="mwBOA">
       <span class="mw-reflink-text" id="mwBOE">
        <span class="cite-bracket" id="mwBOI">
         [
        </span>
        note 3
        <span class="cite-bracket" id="mwBOM">
         ]
        </span>
       </span>
      </a>
     </sup>
     <sup about="#mwt484" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-108"}}' id="cite_ref-108" rel="dc:references" typeof="mw:Extension/ref">
      <a href="#cite_note-108" id="mwBOQ">
       <span class="mw-reflink-text" id="mwBOU">
        <span class="cite-bracket" id="mwBOY">
         [
        </span>
        102
        <span class="cite-bracket" id="mwBOc">
         ]
        </span>
       </span>
      </a>
     </sup>
    </p>
   </td>
   <td id="mwBOg">
    5,223,000
   </td>
   <td id="mwBOk">
    6,025
   </td>
   <td id="mwBOo">
    867
   </td>
  </tr>
  <tr id="mwBOs">
   <td id="mwBOw">
    4
   </td>
   <td align="left" id="mwBO0">
    <span about="#mwt485" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Taiwan"}},"i":0}}]}' id="mwBO4" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_Republic_of_China.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/40px-Flag_of_the_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/60px-Flag_of_the_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt485" href="https://en.wikipedia.org/wiki/Taiwan" id="mwBO8" rel="mw:WikiLink" title="Taiwan">
     Taiwan
    </a>
    <sup about="#mwt486" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-109"}}' id="cite_ref-109" rel="dc:references" typeof="mw:Extension/ref">
     <a data-mw-group="note" href="#cite_note-109" id="mwBPA">
      <span class="mw-reflink-text" id="mwBPE">
       <span class="cite-bracket" id="mwBPI">
        [
       </span>
       note 4
       <span class="cite-bracket" id="mwBPM">
        ]
       </span>
      </span>
     </a>
    </sup>
   </td>
   <td id="mwBPQ">
    23,580,712
   </td>
   <td id="mwBPU">
    35,980
   </td>
   <td id="mwBPY">
    655
   </td>
  </tr>
  <tr id="mwBPc">
   <td id="mwBPg">
    5
   </td>
   <td align="left" id="mwBPk">
    <span about="#mwt487" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"South Korea"}},"i":0}}]}' id="mwBPo" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_South_Korea.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/40px-Flag_of_South_Korea.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/60px-Flag_of_South_Korea.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt487" href="https://en.wikipedia.org/wiki/South_Korea" id="mwBPs" rel="mw:WikiLink" title="South Korea">
     South Korea
    </a>
   </td>
   <td id="mwBPw">
    51,844,834
   </td>
   <td id="mwBP0">
    99,720
   </td>
   <td id="mwBP4">
    520
   </td>
  </tr>
  <tr id="mwBP8">
   <td id="mwBQA">
    6
   </td>
   <td align="left" id="mwBQE">
    <span about="#mwt488" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Lebanon"}},"i":0}}]}' id="mwBQI" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="1920" data-file-type="drawing" data-file-width="2880" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Lebanon.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/40px-Flag_of_Lebanon.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/60px-Flag_of_Lebanon.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt488" href="https://en.wikipedia.org/wiki/Lebanon" id="mwBQM" rel="mw:WikiLink" title="Lebanon">
     Lebanon
    </a>
   </td>
   <td id="mwBQQ">
    5,296,814
   </td>
   <td id="mwBQU">
    10,400
   </td>
   <td id="mwBQY">
    509
   </td>
  </tr>
  <tr id="mwBQc">
   <td id="mwBQg">
    7
   </td>
   <td align="left" id="mwBQk">
    <span about="#mwt489" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Rwanda"}},"i":0}}]}' id="mwBQo" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Rwanda.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/40px-Flag_of_Rwanda.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/60px-Flag_of_Rwanda.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt489" href="https://en.wikipedia.org/wiki/Rwanda" id="mwBQs" rel="mw:WikiLink" title="Rwanda">
     Rwanda
    </a>
   </td>
   <td id="mwBQw">
    13,173,730
   </td>
   <td id="mwBQ0">
    26,338
   </td>
   <td id="mwBQ4">
    500
   </td>
  </tr>
  <tr id="mwBQ8">
   <td id="mwBRA">
    8
   </td>
   <td align="left" id="mwBRE">
    <span about="#mwt490" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Burundi"}},"i":0}}]}' id="mwBRI" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="1000" decoding="async" height="14" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Burundi.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/40px-Flag_of_Burundi.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/60px-Flag_of_Burundi.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt490" href="https://en.wikipedia.org/wiki/Burundi" id="mwBRM" rel="mw:WikiLink" title="Burundi">
     Burundi
    </a>
   </td>
   <td id="mwBRQ">
    12,696,478
   </td>
   <td id="mwBRU">
    27,830
   </td>
   <td id="mwBRY">
    456
   </td>
  </tr>
  <tr id="mwBRc">
   <td id="mwBRg">
    9
   </td>
   <td align="left" id="mwBRk">
    <span about="#mwt491" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Israel"}},"i":0}}]}' id="mwBRo" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="800" data-file-type="drawing" data-file-width="1100" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Israel.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/40px-Flag_of_Israel.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/60px-Flag_of_Israel.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="21"/>
      </span>
     </span>
    </span>
    <a about="#mwt491" href="https://en.wikipedia.org/wiki/Israel" id="mwBRs" rel="mw:WikiLink" title="Israel">
     Israel
    </a>
   </td>
   <td id="mwBRw">
    9,402,617
   </td>
   <td id="mwBR0">
    21,937
   </td>
   <td id="mwBR4">
    429
   </td>
  </tr>
  <tr id="mwBR8">
   <td id="mwBSA">
    10
   </td>
   <td align="left" id="mwBSE">
    <span about="#mwt492" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"India"}},"i":0}}]}' id="mwBSI" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_India.svg" src="//thumb.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/40px-Flag_of_India.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/60px-Flag_of_India.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt492" href="https://en.wikipedia.org/wiki/India" id="mwBSM" rel="mw:WikiLink" title="India">
     India
    </a>
   </td>
   <td id="mwBSQ">
    1,389,637,446
   </td>
   <td id="mwBSU">
    3,287,263
   </td>
   <td id="mwBSY">
    423
   </td>
  </tr>
 </tbody>
</table>

In [ ]:
population_data = pd.DataFrame(columns=["Rank", "Country", "Population", "Area", "Density"])

for row in tables[table_index].tbody.find_all("tr"):
    col = row.find_all("td")
    if col:
        rank = col[0].text.strip()
        country = col[1].text.strip()
        population = col[2].text.strip()
        area = col[3].text.strip()
        density = col[4].text.strip()
        # Yeni satır için geçici bir DataFrame oluştur
        new_row = pd.DataFrame([{"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}])

        ## concat kullanalım
        population_data = pd.concat([population_data,new_row], ignore_index=True)

population_data

  Rank                 Country     Population       Area Density
0    1               Singapore      5,921,231        719   8,235
1    2              Bangladesh    165,650,475    148,460   1,116
2    3  Palestine[note 3][102]      5,223,000      6,025     867
3    4          Taiwan[note 4]     23,580,712     35,980     655
4    5             South Korea     51,844,834     99,720     520
5    6                 Lebanon      5,296,814     10,400     509
6    7                  Rwanda     13,173,730     26,338     500
7    8                 Burundi     12,696,478     27,830     456
8    9                  Israel      9,402,617     21,937     429
9   10                   India  1,389,637,446  3,287,263     423

## 2.yol BeautifulSoup ve read_html kullanarak HTML tablolarından veri kazıyıp bir DataFrame'e aktar

In [15]:
from io import StringIO

pd.read_html(StringIO(str(tables[5])), flavor="bs4")

[   Rank                 Country  Population  Area (km2)  Density (pop/km2)
 0     1               Singapore     5921231         719               8235
 1     2              Bangladesh   165650475      148460               1116
 2     3  Palestine[note 3][102]     5223000        6025                867
 3     4          Taiwan[note 4]    23580712       35980                655
 4     5             South Korea    51844834       99720                520
 5     6                 Lebanon     5296814       10400                509
 6     7                  Rwanda    13173730       26338                500
 7     8                 Burundi    12696478       27830                456
 8     9                  Israel     9402617       21937                429
 9    10                   India  1389637446     3287263                423]

In [16]:
population_data_read_html = pd.read_html(StringIO(str(tables[5])), flavor="bs4")[0]
population_data_read_html

   Rank                 Country  Population  Area (km2)  Density (pop/km2)
0     1               Singapore     5921231         719               8235
1     2              Bangladesh   165650475      148460               1116
2     3  Palestine[note 3][102]     5223000        6025                867
3     4          Taiwan[note 4]    23580712       35980                655
4     5             South Korea    51844834       99720                520
5     6                 Lebanon     5296814       10400                509
6     7                  Rwanda    13173730       26338                500
7     8                 Burundi    12696478       27830                456
8     9                  Israel     9402617       21937                429
9    10                   India  1389637446     3287263                423

## read_html kullanarak HTML tablolarındaki verileri bir DataFrame'e aktarın
### HTML tablolarındaki verileri read_html kullanarak bir DataFrame'e aktarın

In [18]:
dataframe_list = pd.read_html(StringIO(str(data.text)), flavor="bs4")
len(dataframe_list)
dataframe_list[5]

   Rank                 Country  Population  Area (km2)  Density (pop/km2)
0     1               Singapore     5921231         719               8235
1     2              Bangladesh   165650475      148460               1116
2     3  Palestine[note 3][102]     5223000        6025                867
3     4          Taiwan[note 4]    23580712       35980                655
4     5             South Korea    51844834       99720                520
5     6                 Lebanon     5296814       10400                509
6     7                  Rwanda    13173730       26338                500
7     8                 Burundi    12696478       27830                456
8     9                  Israel     9402617       21937                429
9    10                   India  1389637446     3287263                423

## İstediğimiz belirli tabloyu seçmek için `match` parametresini de kullanabiliriz. Eğer tablo, belirtilen metinle eşleşen bir dizge içeriyorsa, bu tablo okunacaktır.

In [22]:
heading = soup.find("h3", {"id": "Most_densely_populated_countries"})

table = heading.find_next("table")
df = pd.read_html(StringIO(str(table)))[0]
print(df.head())

   Rank                 Country  Population  Area (km2)  Density (pop/km2)
0     1               Singapore     5921231         719               8235
1     2              Bangladesh   165650475      148460               1116
2     3  Palestine[note 3][102]     5223000        6025                867
3     4          Taiwan[note 4]    23580712       35980                655
4     5             South Korea    51844834       99720                520