In [1]:
import pandas as pd

### 'x' adında bir sözlük tanımlayın

x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 
     'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}

### Sözlüğü Dataframe'e dönüştür
df1 = pd.DataFrame(x)
df1

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

## Sütun seçimi
Pandas DataFrame'de bir sütunu seçmek için, sütunlara sütun adlarıyla erişebiliriz.

In [2]:
## ID sütununa erişin ve x'e atayalım
X = df1["ID"]
X

0    1
1    2
2    3
3    4
Name: ID, dtype: int64

In [3]:
## TYPE() fonsiyonunu kullanarak X 'in türüne bak
type(x)     ## dict = sözlük

dict

## Birden fazla sütuna erişim

In [4]:
## Departman, Maaş ve Kimlik sütunlarına ait verileri alalım.
z = df1[["Department", "Salary", "ID"]]
z

        Department  Salary  ID
0  Architect Group  100000   1
1   Software Group   80000   2
2      Design Team   50000   3
3   Infrastructure   60000   4

## Quiz 1

In [5]:
new = {"Student": ["David", "Samuel", "Terry", "Evan"],
      "Age": [27,24,22,32],
      "Country":["UK", "Canada", "China", "USA"],
      "Course": ["Python", "Data Structures", "Machine Learning", "Web Development"],
      "Marks": [85,72,89,76]}

df = pd.DataFrame(new)
df

  Student  Age Country            Course  Marks
0   David   27      UK            Python     85
1  Samuel   24  Canada   Data Structures     72
2   Terry   22   China  Machine Learning     89
3    Evan   32     USA   Web Development     76

### Problem 1: Notlar sütununu alın ve b değişkenine atayın.

In [6]:
b = df["Marks"]
b

0    85
1    72
2    89
3    76
Name: Marks, dtype: int64

### Problem 2: Ülke ve Kurs sütunlarını alın ve c değişkenine atayın.

In [7]:
c = df[["Country", "Course"]]
c

  Country            Course
0      UK            Python
1  Canada   Data Structures
2   China  Machine Learning
3     USA   Web Development

### loc[satır_etiketi, sütun_etiketi]
### iloc(), indeks tabanlı bir seçme yöntemidir; yani belirli bir satır/sütunu seçmek için yönteme bir tamsayı indeksi geçirmemiz gerekir. Bu yöntem, kendisine geçirilen aralığın son öğesini içermez.
iloc[satır_indeksi, sütun_indeksi]

In [8]:
# İlk satır ve ilk sütundaki değere erişin
print(df1.iloc[0, 0])

# Birinci satırdaki ve üçüncü sütundaki değere erişin
print(df1.iloc[0, 2])

# Sütuna adını kullanarak erişin
print(df1.loc[0, "Salary"])

Rose
Architect Group
100000

#### 'df2' adında yeni bir veri çerçevesi oluşturalım ve 'df'yi ona atayalım. Şimdi, set_index() yöntemini kullanarak "Student" sütununu indeks sütunu olarak ayarlayalım.

In [10]:
df2 = df1
df2 = df2.set_index("Name")

In [11]:
#Yeni veri çerçevesinin ilk 5 satırını görüntülemek için
df2.head()

# Şimdi, sütuna adını kullanarak erişelim.
df2.loc["Jane", "Salary"]

np.int64(50000)

In [13]:
# Yeni oluşturulan df2 veri çerçevesinde Jane'in bölümünü almak için loc() fonksiyonunu kullanın.
df2.loc["Jane", "Department"]

'Design Team'

In [ ]:
## Yeni oluşturulan df2 veri çerçevesinde Mary'nin maaşını almak için iloc() fonksiyonunu kullanın.
df2.iloc[3, 2]
# df2.loc["Mary", "Salary"]

np.int64(60000)

## Alıştırma 3: Dilimleme
Bir dizi satırı dilimlemek için şu sözdizimini kullanırsınız: data[başlangıç:bitiş]

In [19]:
## Eski veri çerçevesi df'yi kullanarak dilimleme işlemini yapalım
df1.iloc[0:2, 0:3 ]

   Name  ID       Department
0  Rose   1  Architect Group
1  John   2   Software Group

In [21]:
#Eski veri çerçevesi df üzerinde loc() fonksiyonunu kullanarak dilimleme işlemini yapalım; 
# burada index sütununda 0, 1, 2 etiketleri bulunmaktadır.
df1.loc[0:2, "ID": "Department"]

   ID       Department
0   1  Architect Group
1   2   Software Group
2   3      Design Team

In [22]:
## Yeni df2 veri çerçevesinde, indeks sütunu "Name" olan ve etiketleri "Rose", "John" ve "Jane" olan bir alanda,
#  loc() fonksiyonunu kullanarak dilimleme işlemini yapalım.
df2.loc["Rose":"Jane", "ID": "Department"]

      ID       Department
Name
Rose   1  Architect Group
John   2   Software Group
Jane   3      Design Team