In [1]:
import pandas as pd
import numpy as np
from nba_api.stats.static import teams
import matplotlib.pyplot as plt
import requests

In [2]:
dict_= {"a": [11,21,31], "b": [12,22,32]}
df = pd.DataFrame(dict_)

In [3]:
nba_teams = teams.get_teams()
df1 = pd.DataFrame(nba_teams)
df1.head()

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966

In [4]:
df_warriors = df1[df1['nickname']== "Warriors"]
df_warriors

,id,full_name,abbreviation,nickname,city,state,year_founded
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946

In [5]:
id_warriors = df_warriors[["id"]].values[0][0]
id_warriors

np.int64(1610612744)

# Dışardan Apı ile çekme

In [6]:
## Github reposu 

url = "https://raw.githubusercontent.com/toUpperCase78/formula1-datasets/master/Formula1_2023season_raceResults.csv"
df_f1 = pd.read_csv(url)
df_f1.head()

,Track,Position,No,Driver,Team,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time
0,Bahrain,1,1,Max Verstappen,Red Bull Racing Honda RBPT,1,57,1:33:56.736,25,No,1:36.236
1,Bahrain,2,11,Sergio Perez,Red Bull Racing Honda RBPT,2,57,+11.987,18,No,1:36.344
2,Bahrain,3,14,Fernando Alonso,Aston Martin Aramco Mercedes,5,57,+38.637,15,No,1:36.156
3,Bahrain,4,55,Carlos Sainz,Ferrari,4,57,+48.052,12,No,1:37.130
4,Bahrain,5,44,Lewis Hamilton,Mercedes,7,57,+50.977,10,No,1:36.546

In [7]:
## direkt siteden çekmek için
import requests

In [ ]:
filename = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Labs/Golden_State.pkl"

def dowland(url, filename):                 ## dışarıdan bir url ve kaydedilecek dosya adı filename al
    istek = requests.get(url)               ## url'yi getir
    if istek.status_code ==200:             ## başarılı çekersen içeri gir
        with open(filename, "wb") as f:     ## yeni dosya aç bozmadan yaz işi bitince kapa
            f.write(istek.content)

# dowland(filename, "GoldenState.pkl")      ## başarılı indi belge

df = pd.read_pickle("GoldenState.pkl")
df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22019,1610612744,GSW,Golden State Warriors,1521900066,2019-07-12,GSW vs. LAL,L,200,87,...,0.800,13.0,29.0,42.0,13,10.0,3,11.0,21,3.2
1,22019,1610612744,GSW,Golden State Warriors,1521900058,2019-07-10,GSW @ DEN,W,201,73,...,0.867,7.0,27.0,34.0,10,11.0,7,20.0,20,-8.0
2,22019,1610612744,GSW,Golden State Warriors,1521900039,2019-07-08,GSW @ LAL,W,200,88,...,0.621,8.0,29.0,37.0,21,10.0,4,13.0,22,8.0
3,22019,1610612744,GSW,Golden State Warriors,1521900020,2019-07-07,GSW vs. TOR,W,201,80,...,0.923,6.0,37.0,43.0,18,8.0,3,20.0,25,10.0
4,22019,1610612744,GSW,Golden State Warriors,1521900007,2019-07-05,GSW vs. CHA,L,200,85,...,0.889,8.0,28.0,36.0,19,9.0,3,13.0,15,-8.0

# F1 Yarisi

In [10]:
import pandas as pd

# 1950'den günümüze tüm F1 yarış sonuçları
url = "https://raw.githubusercontent.com/theOehrly/Fast-F1/master/fastf1/datasets/sample_data.csv"
# Alternatif doğrudan yarış sonuçları tablosu:
results_url = "https://raw.githubusercontent.com/toUpperCase78/formula1-datasets/master/Formula1_2023season_raceResults.csv"

df_f1 = pd.read_csv(results_url)
df_f1.head()

,Track,Position,No,Driver,Team,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time
0,Bahrain,1,1,Max Verstappen,Red Bull Racing Honda RBPT,1,57,1:33:56.736,25,No,1:36.236
1,Bahrain,2,11,Sergio Perez,Red Bull Racing Honda RBPT,2,57,+11.987,18,No,1:36.344
2,Bahrain,3,14,Fernando Alonso,Aston Martin Aramco Mercedes,5,57,+38.637,15,No,1:36.156
3,Bahrain,4,55,Carlos Sainz,Ferrari,4,57,+48.052,12,No,1:37.130
4,Bahrain,5,44,Lewis Hamilton,Mercedes,7,57,+50.977,10,No,1:36.546